### ISSUE TITLE
Table Names not Created

### ISSUE THREAD

**Issue by ghost** [ignasbernotas/laravel-model-generator#12]
Your readme is incorrect, the package does not produce a `$table` property in the model, since it's not included in the stub:

``` php
<?php

namespace DummyNamespace;

use Illuminate\Database\Eloquent\Model;

/**
 * Class DummyClass
 */
class DummyClass extends {{extends}}
{

    {{timestamps}}

    {{fillable}}

    {{guarded}}

    {{getters}}

    {{setters}}


}
```

Please either adjust the readme or the package for accuracy.

Thanks.

**Comment by iberflow** [comment]
Fixed with #16

**Comment by gitllermopalafox** [comment]
Hi,

I'm using Laravel 5.0.35 and PHP 5.6.10, when I run `php artisan make:models` I get the classes but with 'DummyNamespace' and 'DummyClass'.

Do you think the laravel version is causing this?

**Comment by iberflow** [comment]
Hi,

Yeah, in Laravel 5.1 they changed the "tags" to "Dummy*" therefore it doesn't work for you.

Regards,
Ignas
