### ISSUE TITLE
Command "make:models" is not defined.

### ISSUE THREAD

**Issue by ghost** [ignasbernotas/laravel-model-generator#25]
I tried using it with lumen -- following the install directions, but  "php artisan make:models" gives this error:

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "make:models" is not defined.
  Did you mean this?
      make:migration
```

Am I doing something wrong, or is this not supported with lumen?

**Comment by iberflow** [comment]
Hi, are you sure you've registered the service provider? :) if so, please check what your current environment is set.

**Comment by ghost** [comment]
Thanks for your help. It was a registration issue.

**Comment by allan-api** [comment]
you can execute `php artisan list`;
test `php artisan make:model ClassName`
