### ISSUE TITLE
Call to undefined method Iber\Generator\Commands\MakeModelsCommand::parseName()

### ISSUE THREAD

**Issue by BhawnaBhati** [ignasbernotas/laravel-model-generator#35]
I am using Laravel 5.4. I got following error after correcting setFetchMode issue.

Call to undefined method Iber\Generator\Commands\MakeModelsCommand::parseName()
in vendor\ignasbernotas\laravel-model-generator\src\Commands\MakeModelsCommand.php on line 178

**Comment by iberflow** [comment]
Fixed with 006fbe9 and released in 1.1.5
