### ISSUE TITLE
Unable to Execute Command

### ISSUE THREAD

**Issue by CLOUGH** [ignasbernotas/laravel-model-generator#36]
Hi, im using laravel 5.3 and I was not able to execute the command `php artisan migrate:models` after installing the package. I got the following error message.

  ```Call to undefined method Iber\Generator\Commands\MakeModelsCommand::qualifyClass()```

**Comment by iberflow** [comment]
Should be fixed now :)

**Comment by CLOUGH** [comment]
That change resolved the issue
