### ISSUE TITLE
not being able to install it 

### ISSUE THREAD

**Issue by sandip12** [ignasbernotas/laravel-model-generator#7]
hi please guide to install , where do we place the folder , installation guide incomplete

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Iber\Generator\ModelGeneratorProvider' not found

**Comment by pionl** [comment]
Hi,
did you run the 

> composer install ?

You can run require the package via composer like this:

> composer require ignasbernotas/laravel-model-generator 

It will update the composer.json and install the library with updated autoload.

**Comment by sandip12** [comment]
hello. thanks .
